Feat(Task-1): As a developer, I want a solid start point for the Weather Project
SamuFigueirido/CaelumWeather pull request #1
Opened 2019-04-30 14:00 UTC by SamuFigueirido

2019-04-30 14:36 UTC, diegopf requested changes
As starting point, do not commit your node_modules into your repository :) Add the folder to the .gitignore and remove them from the branch

2019-05-02 07:27 UTC, eloydotco requested changes
Add /node_modules to .gitignore file

2019-05-02 09:50 UTC, diegopf requested changes

2019-05-02 09:50 UTC, diegopf commented on .gitignore
> +node_modules/
You should also add dist folder here

2019-05-02 09:50 UTC, diegopf commented on config/webpack.config.js
> +    devServer: {
You should split the specific environment configuration between different files

2019-05-02 09:50 UTC, diegopf commented on package.json
> +    "build": "webpack --mode production --config ./config/webpack.config.js"
You should make use of HtmlWebpackPlugin in order to produce the index.html to serve your bundle

2019-05-02 14:38 UTC, eloydotco requested changes

2019-05-02 14:38 UTC, gbtec-ext-eloycastelo commented on config/webpack.config.js
> +var HtmlWebpackPlugin = require('html-webpack-plugin');
Use const/let instead of var

2019-05-02 14:38 UTC, gbtec-ext-eloycastelo commented on src/app/app.module.js
> +angular.module('app', [
why this line break??

2019-05-02 14:38 UTC, gbtec-ext-eloycastelo commented on src/index.html
> +<body ng-app="app" ng-strict-di ng-cloak>
I think some html tags are missing here...

2019-05-02 14:42 UTC, gbtec-ext-jorgevillar requested changes

2019-05-02 14:42 UTC, gbtec-ext-jorgevillar commented on config/webpack.config.js
> +    plugins: [new HtmlWebpackPlugin()],
I think that you need to configure the pluging, at least adding the filename(resulting html) and template(your main html route) options

2019-05-03 06:28 UTC, eloydotco approved these changes

2019-05-03 07:55 UTC, diegopf approved these changes

2019-05-03 11:10 UTC, gbtec-ext-jorgevillar approved these changes

2019-05-03 11:17 UTC, merged