Feat(Task-2): As a developer, I want to use Visual libraries
SamuFigueirido/CaelumWeather pull request #2
Opened 2019-05-02 09:04 UTC by SamuFigueirido

2019-05-02 09:07 UTC, gbtec-ext-eloycastelo commented
Please, add node_modules folder to .gitignore file

2019-05-02 14:41 UTC, eloydotco requested changes

2019-05-02 14:41 UTC, eloydotco commented on src/index.html
> +<body>
Missing html tags

2019-05-02 14:41 UTC, eloydotco commented on src/app/app.module.js
> +angular.module('app', [
It's a good practice add an empty line between import statemens and the rest of the code

2019-05-03 06:25 UTC, eloydotco approved these changes

2019-05-03 10:14 UTC, gbtec-ext-jorgevillar approved these changes

2019-05-03 11:32 UTC, merged