Feat(Task-3): As a developer, I want to manage the screen change easily
SamuFigueirido/CaelumWeather pull request #3
Opened 2019-05-03 08:49 UTC by SamuFigueirido

2019-05-03 11:46 UTC, gbtec-ext-jorgevillar requested changes

2019-05-03 11:46 UTC, gbtec-ext-jorgevillar commented on src/app/app.module.js
> +myApp.config(['$stateProvider', function(provider) {
Create the config in another file an import it here

2019-05-03 11:46 UTC, gbtec-ext-jorgevillar commented on src/app/app.module.js
> +const myApp = angular.module('app', [uirouter, ngMaterial, ngAnimate, ngAria])
Create the modules in this way
![image](https://user-images.githubusercontent.com/37654233/57135436-b0864180-6da9-11e9-9165-46026fffc0f8.png)

2019-05-03 11:46 UTC, gbtec-ext-jorgevillar commented on src/app/hello/hello.js
> +export default AppComponent;
And components like this

![image](https://user-images.githubusercontent.com/37654233/57135462-c8f65c00-6da9-11e9-962c-c669a85a67a4.png)

2019-05-03 12:07 UTC, eloydotco approved these changes

2019-05-03 12:07 UTC, eloydotco commented on .vscode/settings.json
> +{
add .vscode folder to .gitignore

2019-05-06 14:43 UTC, gbtec-ext-jorgevillar approved these changes

2019-05-06 14:44 UTC, merged